import type { Metadata } from "next";
import "../globals.css";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Account Manager - Paso Libre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen overflow-x-hidden bg-white text-gray-800">
      <div className="h-28 bg-[#0d4db0]"></div>
      <div>{children}</div>
      <Footer />
    </main>
  );
}
