// import { faker } from "@faker-js/faker";

export const RECENT_FORMS = [
  {
    // id: crypto.randomUUID(),
    id: "bienestar",
    title: "Construyamos Bienestar Juntxs 🏳️‍⚧️🏳️‍🌈",
    description:
      "Con estas preguntas buscamos entender mejor tus necesidades, intereses y experiencias para poder crear actividades, espacios y esfuerzos que realmente apoyen tu bienestar y el de nuestra comunidad. Tu voz nos ayuda a que Pasolibre siga creciendo de forma auténtica, inclusiva y alineada con lo que de verdad importa. Gracias por tomarte el tiempo 🩵\n\nNota: Estamos comenzando y quizás no podamos cubrir todas las necesidades de inmediato, pero tus respuestas nos ayudan a encaminarnos y construir poco a poco los espacios que nuestra comunidad merece.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    blocks: [
      {
        id: crypto.randomUUID(),
        type: "title",
        title: "Cuéntanos un poquito de ti 🩵",
        description: "",
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Edad",
        questionType: "multiple_choice",
        required: true,
        options: [
          "15–17",
          "18–24",
          "25–34",
          "35–44",
          "45–54",
          "55+",
          "Prefiero no decir",
        ],
      },
      {
        // id: crypto.randomUUID(),
        id: "movie-night",
        type: "question",
        label: "Municipio donde resides",
        questionType: "dropdown",
        required: true,
        options: [
          "Adjuntas",
          "Aguada",
          "Aguadilla",
          "Aguas Buenas",
          "Aibonito",
          "Añasco",
          "Arecibo",
          "Arroyo",
          "Barceloneta",
          "Barranquitas",
          "Bayamón",
          "Cabo Rojo",
          "Caguas",
          "Camuy",
          "Canóvanas",
          "Carolina",
          "Cataño",
          "Cayey",
          "Ceiba",
          "Ciales",
          "Cidra",
          "Coamo",
          "Comerío",
          "Corozal",
          "Culebra",
          "Dorado",
          "Fajardo",
          "Florida",
          "Guánica",
          "Guayama",
          "Guayanilla",
          "Guaynabo",
          "Gurabo",
          "Hatillo",
          "Hormigueros",
          "Humacao",
          "Isabela",
          "Jayuya",
          "Juana Díaz",
          "Juncos",
          "Lajas",
          "Lares",
          "Las Marías",
          "Las Piedras",
          "Loíza",
          "Luquillo",
          "Manatí",
          "Maricao",
          "Maunabo",
          "Mayagüez",
          "Moca",
          "Morovis",
          "Naguabo",
          "Naranjito",
          "Orocovis",
          "Patillas",
          "Peñuelas",
          "Ponce",
          "Quebradillas",
          "Rincón",
          "Río Grande",
          "Sabana Grande",
          "Salinas",
          "San Germán",
          "San Juan",
          "San Lorenzo",
          "San Sebastián",
          "Santa Isabel",
          "Toa Alta",
          "Toa Baja",
          "Trujillo Alto",
          "Utuado",
          "Vega Alta",
          "Vega Baja",
          "Vieques",
          "Villalba",
          "Yabucoa",
          "Yauco",
        ],
      },
    ],
  },

  {
    id: crypto.randomUUID(),
    title: "🎬 Movie Night Vote",
    description:
      "Help us pick the perfect movie for our next community movie night! Cast your vote and let us know what you’d love to watch together 🍿",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    blocks: [
      {
        id: crypto.randomUUID(),
        type: "title",
        title: "Vote for Movie Night 🍿",
        description:
          "Choose one option below. The movie with the most votes wins!",
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Which movie should we watch?",
        questionType: "multiple_choice",
        required: true,
        options: [
          "Everything Everywhere All at Once",
          "Moonlight",
          "Bottoms",
          "Pride",
          "The Rocky Horror Picture Show",
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Preferred genre (optional)",
        questionType: "checkbox",
        required: false,
        options: ["Comedy", "Drama", "Romance", "Horror", "Documentary"],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Any other movie suggestions?",
        questionType: "long_text",
        required: false,
        options: [],
      },
    ],
  },
];

export const FORM_TEMPLATES = [
  {
    id: crypto.randomUUID(),
    title: "Event Registration Form",
    description: "Please fill out this form to register for the event.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    blocks: [
      {
        id: crypto.randomUUID(),
        type: "title",
        title: "Welcome to Our Event 🎉",
        description:
          "We’re excited to have you. Please answer the questions below.",
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Full name",
        questionType: "short_text",
        required: true,
        options: [],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Email address",
        questionType: "short_text",
        required: true,
        options: [],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "How did you hear about this event?",
        questionType: "multiple_choice",
        required: false,
        options: ["Instagram", "Friend", "Email", "Other"],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Would you like to receive updates?",
        questionType: "boolean",
        required: false,
        options: [],
      },
    ],
  },

  {
    id: crypto.randomUUID(),
    title: "Customer Feedback Survey",
    description: "Your feedback helps us improve our services.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    blocks: [
      {
        id: crypto.randomUUID(),
        type: "title",
        title: "Tell Us What You Think",
        description: "",
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "How satisfied are you with our service?",
        questionType: "rating",
        required: true,
        options: [],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "What did you like the most?",
        questionType: "long_text",
        required: false,
        options: [],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "What can we improve?",
        questionType: "long_text",
        required: false,
        options: [],
      },
    ],
  },

  {
    id: crypto.randomUUID(),
    title: "Job Application",
    description: "Apply for the open position by completing this form.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    blocks: [
      {
        id: crypto.randomUUID(),
        type: "section",
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Position you are applying for",
        questionType: "dropdown",
        required: true,
        options: ["Frontend Developer", "Backend Developer", "Designer"],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Years of experience",
        questionType: "number",
        required: true,
        options: [],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Tell us about yourself",
        questionType: "long_text",
        required: true,
        options: [],
      },
      {
        id: crypto.randomUUID(),
        type: "question",
        label: "Skills",
        questionType: "checkbox",
        required: false,
        options: ["React", "Node.js", "UI/UX", "SQL"],
      },
    ],
  },
  ...RECENT_FORMS,
];

// const fakePerson = () => {
//   const firstName = faker.person.firstName();
//   const lastName = faker.person.lastName();

//   return {
//     firstName,
//     lastName,
//     fullName: `${firstName} ${lastName}`,
//   };
// };

// export const FAKE_RESPONSES = [
//   // ----------- Construyamos Bienestar Juntxs -----------------
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "18–24",
//       "Municipio donde resides": "San Juan",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "25–34",
//       "Municipio donde resides": "Bayamón",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "35–44",
//       "Municipio donde resides": "Ponce",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "55+",
//       "Municipio donde resides": "Mayagüez",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "45–54",
//       "Municipio donde resides": "Caguas",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "18–24",
//       "Municipio donde resides": "Carolina",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "Prefiero no decir",
//       "Municipio donde resides": "Guaynabo",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "15–17",
//       "Municipio donde resides": "Toa Baja",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "25–34",
//       "Municipio donde resides": "Trujillo Alto",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "35–44",
//       "Municipio donde resides": "Humacao",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "45–54",
//       "Municipio donde resides": "Mayagüez",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "55+",
//       "Municipio donde resides": "Fajardo",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "18–24",
//       "Municipio donde resides": "San Sebastián",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "35–44",
//       "Municipio donde resides": "Bayamón",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "bienestar",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       Edad: "25–34",
//       "Municipio donde resides": "Arecibo",
//     },
//   },

//   // ------------ Movie Night Vote -------------------

//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Everything Everywhere All at Once",
//       "Preferred genre (optional)": ["Comedy", "Drama"],
//       "Any other movie suggestions?": "I love quirky indie films!",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Moonlight",
//       "Preferred genre (optional)": ["Drama"],
//       "Any other movie suggestions?": "",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Bottoms",
//       "Preferred genre (optional)": ["Comedy", "Romance"],
//       "Any other movie suggestions?": "Can we do a double feature?",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Pride",
//       "Preferred genre (optional)": ["Drama", "Documentary"],
//       "Any other movie suggestions?": "I’ve never seen this one!",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "The Rocky Horror Picture Show",
//       "Preferred genre (optional)": ["Comedy", "Horror"],
//       "Any other movie suggestions?": "Classic cult favorite!",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Moonlight",
//       "Preferred genre (optional)": ["Drama", "Romance"],
//       "Any other movie suggestions?": "Love this movie!",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Bottoms",
//       "Preferred genre (optional)": [],
//       "Any other movie suggestions?": "",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Pride",
//       "Preferred genre (optional)": ["Documentary"],
//       "Any other movie suggestions?": "",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Everything Everywhere All at Once",
//       "Preferred genre (optional)": ["Comedy"],
//       "Any other movie suggestions?": "Excited to watch!",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "The Rocky Horror Picture Show",
//       "Preferred genre (optional)": ["Horror", "Comedy"],
//       "Any other movie suggestions?": "Can't wait!",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Moonlight",
//       "Preferred genre (optional)": ["Drama", "Romance"],
//       "Any other movie suggestions?": "Such a beautiful story.",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Bottoms",
//       "Preferred genre (optional)": ["Comedy", "Romance"],
//       "Any other movie suggestions?": "Love it!",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Pride",
//       "Preferred genre (optional)": ["Drama"],
//       "Any other movie suggestions?": "",
//     },
//   },
//   {
//     id: crypto.randomUUID(),
//     formId: "movie-night",
//     respondent: fakePerson(),
//     submittedAt: faker.date.recent(60).toISOString(),
//     answers: {
//       "Which movie should we watch?": "Everything Everywhere All at Once",
//       "Preferred genre (optional)": [],
//       "Any other movie suggestions?": "Highly recommended!",
//     },
//   },
// ];
