import type { Metadata } from "next";
import "../globals.css";
import { ProvidersProvider } from "../context/providers/providersContext";

export const metadata: Metadata = {
  title: "Manage Community Feedback - Paso Libre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen overflow-x-hidden bg-white text-gray-800">
      <ProvidersProvider>
        <div>{children}</div>
      </ProvidersProvider>
    </main>
  );
}
