import type { Metadata } from "next";
import "../globals.css";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Admin Dashboard - Paso Libre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen text-gray-800 bg-white">
      <div className="h-28 bg-[#0d4db0]"></div>
      <main className="grow">{children}</main>
      <Footer />
    </div>
  );
}
