import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Paso Libre CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen overflow-x-hidden bg-white text-gray-800">
      {/* <div className="h-24"></div> */}
      <div>{children}</div>
    </main>
  );
}
