export interface SchedulerForm {
  id: string;
  name_en: string;
  name_es: string;
  price?: number | null;
  city?: string | null;
  country?: string | null;
  zipCode?: string | null;
  zip_code?: string | null;
  locationUrl?: string | null;
  date?: string;
  time?: string;
  scheduleType?: "one-time" | "recurrent";
  streetAddress?: string;
  street_address?: string;
  privacy?: string;
  type?: string;
  description_en?: string;
  description_es?: string;
  details_en?: string;
  details_es?: string;
  recurrence?: string;
  frequency?: string;
  daysOfWeekCsv?: string;
  dayOfMonth?: number | string;
  month?: number | string;
  monthsCsv?: string;
  status?: string;
  createAttendanceSheet?: boolean;
  includeForm?: boolean;
  dressCode?: string;
  dress_code?: string;
  color?: string;
  hosts?: { id: string; name: string }[];
  instructors?: { id: string; name: string }[];
  start?: string;
  imagePositionY?: number;
  imageHeight?: number;
  recurrence_excluded_dates?: string[];
  recurrenceExcludedDates?: string[];
  audioPreviewUrl?: string;
  audioTrackId?: string;
  audioTrackName?: string;
  audioArtistName?: string;
  audioArtworkUrl?: string;
  audioTrackViewUrl?: string;
  audioEnabled?: boolean;
  createdAt?: string;
  created_at?: string;
  occurrenceDate?: string; // new
  location?: string | null; // new
  location_url?: string | null;
  imageUrl?: string | null;
  image_url?: string | null;
  image_height?: number | null;
  image_position_y?: number | null;
  schedule_type?: "one-time" | "recurrent";
  days_of_week_csv?: string;
  day_of_month?: number | string;
  months_csv?: string;
  audio_enabled?: boolean;
  audio_preview_url?: string;
  audio_artwork_url?: string;
  audio_track_name?: string;
  audio_artist_name?: string;
  include_form?: boolean;
  total_members_donated?: number | null;
  total_donations_usd?: number | null;
  created_by?: string | null;
  executionTime?: string | null;
  userHasConfirmed?: boolean;
}

export interface DbEvent {
  id: string;
  name_en: string;
  name_es: string;
  description_en: string;
  description_es: string;
  details_en?: string;
  details_es?: string;
  date: string | null;
  time: string | null;
  schedule_type?: string;
  recurrence?: string;
  days_of_week_csv?: string;
  day_of_month?: number | null;
  month?: number | null;
  months_csv?: string;
  street_address?: string;
  city?: string;
  country?: string;
  zip_code?: string;
  location_url?: string;
  price?: number;
  privacy?: string;
  type?: string;
  status?: string;
  create_attendance_sheet?: boolean;
  include_form?: boolean;
  color?: string | null;
  image_url?: string;
  dress_code?: string | null;
  recurrence_excluded_dates?: string[] | null;
  hosts?: { id: string; name: string }[] | null;
  instructors?: { id: string; name: string }[] | null;
  audio_enabled?: boolean;
  audio_track_id?: string;
  audio_track_name?: string;
  audio_artist_name?: string;
  audio_artwork_url?: string;
  audio_preview_url?: string;
  audio_track_view_url?: string;
  created_at?: string;
}

export type InviteeProfile = {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  language_preference?: string | null;
  is_approved?: boolean;
  account_status?: string | null;
};
