import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Initiatives - Paso Libre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen bg-white text-gray-800">
      <div>{children}</div>
    </main>
  );
}
