import type { Metadata } from "next";
import "../globals.css";

import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: "IT Support - Paso Libre",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="grow">{children}</main>
      <Footer />
    </div>
  );
}
