import type { Metadata } from "next";
import "../globals.css";
import { ProvidersProvider } from "../context/providers/providersContext";

export const metadata: Metadata = {
  title: "Manage Resources - Paso Libre",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen overflow-x-hidden bg-white text-gray-800">
      {/* <div className="h-20"></div> */}
      <ProvidersProvider>
        <div>{children}</div>
      </ProvidersProvider>
    </main>
  );
}
