import type { Metadata } from "next";
import "../../globals.css";


export const metadata: Metadata = {
  title: "Check-In - Paso Libre",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="grow">{children}</main>
    </div>
  );
}
