import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

type EmailLanguage = "en" | "es";

const escapeHtml = (value: string) =>
  String(value || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");

const getLanguage = (value?: string | null): EmailLanguage => {
  const normalized = String(value || "")
    .trim()
    .toLowerCase();

  if (
    normalized === "es" ||
    normalized === "spa" ||
    normalized === "spanish" ||
    normalized === "español"
  ) {
    return "es";
  }

  return "en";
};

const getCopy = (language: EmailLanguage) => {
  const isSpanish = language === "es";

  return {
    missingFields: isSpanish
      ? "Faltan campos requeridos."
      : "Missing required fields.",

    missingResend: isSpanish
      ? "Falta RESEND_API_KEY."
      : "Missing RESEND_API_KEY.",

    attendanceConfirmed: isSpanish
      ? "Asistencia Confirmada"
      : "Attendance Confirmed",

    confirmedTitle: isSpanish
      ? "¡Tu asistencia está confirmada"
      : "You're confirmed",

    attendanceRecorded: isSpanish
      ? "Tu asistencia fue registrada exitosamente para:"
      : "Your attendance has been successfully recorded for:",

    event: isSpanish ? "Evento" : "Event",

    viewCheckIn: isSpanish ? "Ver Check-In del Evento" : "View Event Check-In",

    keepEmail: isSpanish
      ? "Por favor guarda este correo como confirmación de tu asistencia."
      : "Please keep this email as confirmation of your attendance.",

    autoGenerated: isSpanish
      ? "Este mensaje fue generado automáticamente por Paso Libre."
      : "This message was generated automatically from Paso Libre.",

    rightsReserved: isSpanish
      ? "Todos los derechos reservados."
      : "All rights reserved.",

    emailSubject: isSpanish ? "Asistencia Confirmada" : "Attendance Confirmed",

    failedSend: isSpanish
      ? "No se pudo enviar el correo de confirmación."
      : "Failed to send confirmation email.",

    serverError: isSpanish ? "Error del servidor." : "Server error.",
  };
};

export async function POST(req: Request) {
  try {
    const body = await req.json();

    // console.log("send-attendance-confirmation request body:", body);

    const eventId = String(body.eventId || "").trim();
    const eventName = String(body.eventName || "").trim();
    const eventNameEn = String(body.eventNameEn || "").trim();
    const eventNameEs = String(body.eventNameEs || "").trim();

    const eventDate = String(body.eventDate || "").trim();

    const participantName = String(body.participantName || "").trim();

    const participantEmail = String(body.participantEmail || "").trim();

    const participantLanguagePreference = String(
      body.participantLanguagePreference || "en"
    )
      .trim()
      .toLowerCase();

    const checkInUrl = String(body.checkInUrl || "").trim();

    const language = getLanguage(participantLanguagePreference);
    const copy = getCopy(language);

    const localizedEventName =
      language === "es" || participantLanguagePreference === "es"
        ? eventNameEs || eventNameEn || eventName
        : eventNameEn || eventNameEs || eventName;

    if (
      !eventId ||
      !localizedEventName ||
      !participantName ||
      !participantEmail
    ) {
      return NextResponse.json(
        {
          success: false,
          message: copy.missingFields,
          message_en: getCopy("en").missingFields,
          message_es: getCopy("es").missingFields,
        },
        { status: 400 }
      );
    }

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json(
        {
          success: false,
          message: copy.missingResend,
          message_en: getCopy("en").missingResend,
          message_es: getCopy("es").missingResend,
        },
        { status: 500 }
      );
    }

    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

    const logoUrl = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/email-assets/logo-title.png`;

    const eventUrl =
      checkInUrl ||
      `${siteUrl}/check-in/${eventId}?occurrenceDate=${eventDate}`;

    const gradient =
      "linear-gradient(135deg,#34d399 0%, #10b981 50%, #047857 100%)";

    const html = `
      <div style="margin:0;padding:0;background:#f0fdf4;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
        <table width="100%" cellspacing="0" cellpadding="0" style="background:#f0fdf4;padding:32px 16px;">
          <tr>
            <td align="center">
              <table width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#ffffff;border-radius:24px;overflow:hidden;box-shadow:0 18px 45px rgba(15,23,42,0.12);">
                
                <tr>
                  <td style="padding:36px 34px;text-align:center;background:${gradient};">
                    <img
                      src="${logoUrl}"
                      alt="Paso Libre"
                      width="320"
                      style="display:block;margin:0 auto;height:auto;max-width:100%;"
                    />

                    <p style="margin:12px 0 0;color:#dcfce7;font-size:13px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">
                      ${copy.attendanceConfirmed}
                    </p>
                  </td>
                </tr>

                <tr>
                  <td style="padding:34px;">
                    <div style="margin:0 0 24px;text-align:center;">
                      <div style="display:inline-block;width:64px;height:64px;line-height:64px;border-radius:999px;background:#dcfce7;color:#047857;font-size:34px;font-weight:800;">
                        ✓
                      </div>
                    </div>

                    <h2 style="margin:0 0 12px;color:#0f172a;font-size:25px;line-height:1.25;font-weight:800;text-align:center;">
                      ${copy.confirmedTitle}, ${escapeHtml(participantName)}!
                    </h2>

                    <p style="margin:0 0 24px;color:#475569;font-size:15px;line-height:1.75;text-align:center;">
                      ${copy.attendanceRecorded}
                    </p>

                    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:18px;padding:20px;margin-bottom:24px;text-align:center;">
                      <p style="margin:0 0 4px;color:#64748b;font-size:11px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">
                        ${copy.event}
                      </p>

                      <p style="margin:0;color:#0f172a;font-size:18px;font-weight:800;line-height:1.4;">
                        ${escapeHtml(localizedEventName)}
                      </p>
                    </div>

                    <div style="text-align:center;margin-top:10px;">
                      <a
                        href="${eventUrl}"
                        style="display:inline-block;background:${gradient};box-shadow:0 10px 25px rgba(16,185,129,0.28);color:#ffffff;text-decoration:none;padding:14px 26px;border-radius:16px;font-weight:700;font-size:14px;"
                      >
                        ${copy.viewCheckIn}
                      </a>
                    </div>

                    <p style="margin:24px 0 0;color:#64748b;font-size:13px;line-height:1.7;text-align:center;">
                      ${copy.keepEmail}
                    </p>
                  </td>
                </tr>

                <tr>
                  <td style="padding:22px 34px;background:#f8fafc;text-align:center;border-top:1px solid #e2e8f0;">
                    <p style="margin:0;color:#64748b;font-size:12px;line-height:1.6;">
                      ${copy.autoGenerated}
                    </p>

                    <p style="margin:8px 0 0;color:#94a3b8;font-size:11px;">
                      © ${new Date().getFullYear()} Paso Libre. ${
      copy.rightsReserved
    }
                    </p>
                  </td>
                </tr>

              </table>
            </td>
          </tr>
        </table>
      </div>
    `;

    const { error } = await resend.emails.send({
      from: process.env.EMAIL_FROM || "Paso Libre <team@pasolibre.org>",
      to: participantEmail,
      subject: `${copy.emailSubject}: ${localizedEventName}`,
      html,
    });

    if (error) {
      throw new Error(error.message || copy.failedSend);
    }

    return NextResponse.json(
      {
        success: true,
        message: "Attendance confirmation sent successfully.",
        message_en: "Attendance confirmation sent successfully.",
        message_es: "La confirmación de asistencia fue enviada correctamente.",
      },
      { status: 200 }
    );
  } catch (error: unknown) {
    console.error("send-attendance-confirmation error:", error);

    const errorMessage =
      error instanceof Error ? error.message : "Server error.";

    return NextResponse.json(
      {
        success: false,
        message: errorMessage,
        message_en: errorMessage || getCopy("en").serverError,
        message_es: errorMessage || getCopy("es").serverError,
      },
      { status: 500 }
    );
  }
}
